# Generated by Django 6.0.6 on 2026-06-12 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Contratos, Finiquitos, Amonestaciones', max_length=100)),
                ('requiere_firma', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='comunicados_media/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoInduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Resumen de lo que el asesor aprenderá aquí.')),
                ('tipo', models.CharField(choices=[('GENERAL', 'Cultura General RJ (Para todos)'), ('CARTERA', 'Específico por Cartera / Negocio'), ('HABILIDADES', 'Desarrollo de Habilidades (Opcional/Secundario)')], default='GENERAL', max_length=20)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='lms_portadas/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_anonima', models.BooleanField(default=True, help_text='Oculta la identidad del trabajador en los reportes.')),
                ('con_puntaje', models.BooleanField(default=False, help_text='Define si las respuestas acumulan una puntuación métrica.')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('color', models.CharField(default='#183D74', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('ASESOR', 'Asesor'), ('BACKOFFICE', 'Backoffice'), ('CALIDAD', 'Calidad'), ('SUPERVISOR', 'Supervisor'), ('SISTEMAS', 'Sistemas'), ('ADMINISTRATIVO', 'Administrativo'), ('RRHH', 'Recursos Humanos'), ('GERENCIA', 'Gerencia')], default='ASESOR', max_length=50)),
                ('tipo_horario', models.CharField(choices=[('T1', 'Turno Mañana'), ('T2', 'Turno Tarde'), ('TC', 'Turno Completo'), ('PT', 'Part Time')], default='T1', max_length=10)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=1025.0, max_digits=10)),
                ('banco_pago', models.CharField(default='BCP', max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('regimen_laboral', models.CharField(default='Regimen General Mype', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguridad', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boveda_pdf/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador / Pre-visualización'), ('PENDIENTE', 'Pendiente de Firma'), ('COMPLETADO', 'Firmado y Cerrado'), ('ANULADO', 'Anulado / Rechazado')], default='BORRADOR', max_length=20)),
                ('visible_para_empleado', models.BooleanField(default=False, help_text='Activar cuando RRHH decida liberarlo')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_documentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato de Trabajo'), ('BOLETA', 'Boleta de Pago'), ('LIQUIDACION', 'Liquidación de Beneficios'), ('MEMORANDUM', 'Memorándum Interno'), ('OTROS', 'Otros Documentos')], max_length=20)),
                ('titulo', models.CharField(help_text='Ej: Boleta de Pago - Mayo 2026', max_length=150)),
                ('archivo', models.FileField(upload_to='boveda_personal/')),
                ('requiere_firma', models.BooleanField(default=False)),
                ('esta_firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_digitales', to='intranet.colaborador')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Examen de Conocimientos', max_length=200)),
                ('instrucciones', models.TextField(blank=True)),
                ('puntaje_aprobatorio', models.IntegerField(default=14, help_text='Nota mínima para pasar (Ej: 14/20 o 70/100)')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='intranet.cursoinduccion')),
            ],
        ),
        migrations.CreateModel(
            name='FirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_firma', models.CharField(choices=[('EMPLEADO', 'Colaborador'), ('SUPERVISOR', 'Supervisor Directo'), ('RRHH', 'Recursos Humanos'), ('LEGAL', 'Representante Legal')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1, help_text='1 firma primero, 2 firma después...')),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('token_utilizado', models.CharField(blank=True, max_length=6, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='intranet.documentogenerado')),
                ('firmante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('VIDEO_MP4', 'Video Subido (MP4)'), ('YOUTUBE', 'Video Externo (YouTube/Vimeo)'), ('DOCUMENTO', 'PDF / Word / Diapositivas PPT'), ('TEXTO', 'Artículo / Políticas en Texto Rico')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='lms_materiales/')),
                ('url_externa', models.URLField(blank=True, help_text='Link de YouTube o Drive', null=True)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='intranet.cursoinduccion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Iniciar'), ('EN_CURSO', 'Viendo Materiales'), ('EVALUANDO', 'Rindiendo Examen'), ('COMPLETADO', 'Aprobado y Finalizado'), ('REPROBADO', 'Examen Reprobado (Requiere Reintento)')], default='PENDIENTE', max_length=20)),
                ('nota_obtenida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_matriculados', to='intranet.colaborador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cursoinduccion')),
                ('materiales_vistos', models.ManyToManyField(blank=True, to='intranet.materialformativo')),
            ],
            options={
                'unique_together': {('colaborador', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='MensajeInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(default='Sin Asunto', max_length=200)),
                ('cuerpo', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='mensajeria_adjuntos/')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='intranet.colaborador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='intranet.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='cartera_vinculada',
            field=models.ForeignKey(blank=True, help_text="Solo si el tipo es 'Específico por Cartera'", null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.negocio'),
        ),
        migrations.CreateModel(
            name='CandidatoOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('puesto_esperado', models.CharField(default='ASESOR', max_length=100)),
                ('doc_cv', models.BooleanField(default=False, verbose_name='CV Actualizado')),
                ('doc_dni', models.BooleanField(default=False, verbose_name='Copia de DNI')),
                ('doc_antecedentes', models.BooleanField(default=False, verbose_name='Antecedentes Policiales/Penales')),
                ('doc_recibo_servicios', models.BooleanField(default=False, verbose_name='Recibo de Agua/Luz')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso de Inducción'), ('COMPLETADO', 'Inducción Completada / En Planilla')], default='EN_PROCESO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progreso', to='intranet.colaborador')),
                ('campaña_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.negocio')),
            ],
            options={
                'verbose_name': 'Candidato Onboarding',
                'verbose_name_plural': 'Candidatos Onboarding',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('negocio_postula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Contrato Part-Time Asesores', max_length=200)),
                ('archivo_word', models.FileField(help_text='Sube el archivo .docx con las variables {{ variables }}', upload_to='plantillas_docs/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.categoriadocumento')),
            ],
        ),
        migrations.AddField(
            model_name='documentogenerado',
            name='plantilla_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.plantilladocumento'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('ABIERTA', 'Pregunta Abierta (Texto Libre)'), ('CERRADA', 'Pregunta Cerrada (Opciones Sí / No)')], default='ABIERTA', max_length=20)),
                ('puntos_si', models.IntegerField(default=0, help_text='Puntaje si responde SÍ (Solo si la encuesta tiene puntaje)')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='intranet.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('ABIERTA', 'Respuesta Abierta (Desarrollo)'), ('MULTIPLE', 'Opción Múltiple (Una correcta)'), ('CASILLAS', 'Casillas (Varias correctas)'), ('ORDENAR', 'Ordenar Pasos Lógicos'), ('RELACIONAR', 'Relacionar Conceptos')], max_length=20)),
                ('imagen_apoyo', models.ImageField(blank=True, null=True, upload_to='lms_preguntas/')),
                ('puntos', models.IntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('configuracion_json', models.JSONField(blank=True, default=dict)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='intranet.evaluacioncurso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_json', models.JSONField(default=dict)),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intranet.matriculacurso')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.preguntaevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_si_no', models.BooleanField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(blank=True, help_text='Vacío si la encuesta es anónima.', null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.colaborador')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intranet.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=50)),
                ('comentarios_rrhh', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.colaborador')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARDANZA', 'Justificar Tardanza'), ('INASISTENCIA', 'Justificar Falta'), ('MEDICO', 'Descanso Médico / Salud'), ('SOPORTE', 'Soporte TI / Otros')], default='TARDANZA', max_length=20)),
                ('motivo', models.TextField()),
                ('adjunto_comprobante', models.FileField(blank=True, null=True, upload_to='tickets_evidencias/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.colaborador')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_revisados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('f1_ingreso', models.TimeField(blank=True, null=True)),
                ('f2_salida_almuerzo', models.TimeField(blank=True, null=True)),
                ('f3_retorno_almuerzo', models.TimeField(blank=True, null=True)),
                ('f4_salida', models.TimeField(blank=True, null=True)),
                ('f7_salida_break', models.TimeField(blank=True, null=True)),
                ('f8_retorno_break', models.TimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.colaborador')),
            ],
            options={
                'unique_together': {('colaborador', 'fecha')},
            },
        ),
    ]
