# Generated by Django 6.0.6 on 2026-06-12 21:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='intranet.colaborador'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='candidatoonboarding',
            name='dni',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='candidatoonboarding',
            name='doc_antecedentes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatoonboarding',
            name='doc_cv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatoonboarding',
            name='doc_dni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatoonboarding',
            name='doc_recibo_servicios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatoonboarding',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso de Inducción'), ('COMPLETADO', 'Inducción Completada / En Planilla')], db_index=True, default='EN_PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoriadocumento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='dni',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rol',
            field=models.CharField(choices=[('ASESOR', 'Asesor'), ('BACKOFFICE', 'Backoffice'), ('CALIDAD', 'Calidad'), ('SUPERVISOR', 'Supervisor'), ('SISTEMAS', 'Sistemas'), ('ADMINISTRATIVO', 'Administrativo'), ('RRHH', 'Recursos Humanos'), ('GERENCIA', 'Gerencia')], db_index=True, default='ASESOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cursoinduccion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='cursoinduccion',
            name='cartera_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.negocio'),
        ),
        migrations.AlterField(
            model_name='documentogenerado',
            name='codigo_seguridad',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentogenerado',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador / Pre-visualización'), ('PENDIENTE', 'Pendiente de Firma'), ('COMPLETADO', 'Firmado y Cerrado'), ('ANULADO', 'Anulado / Rechazado')], db_index=True, default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentogenerado',
            name='visible_para_empleado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='esta_firmado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='tipo',
            field=models.CharField(choices=[('CONTRATO', 'Contrato de Trabajo'), ('BOLETA', 'Boleta de Pago'), ('LIQUIDACION', 'Liquidación de Beneficios'), ('MEMORANDUM', 'Memorándum Interno'), ('OTROS', 'Otros Documentos')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='con_puntaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='es_anonima',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncurso',
            name='puntaje_aprobatorio',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='fecha_fin',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='firmadigital',
            name='firmado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='firmadigital',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='materialformativo',
            name='url_externa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matriculacurso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Iniciar'), ('EN_CURSO', 'Viendo Materiales'), ('EVALUANDO', 'Rindiendo Examen'), ('COMPLETADO', 'Aprobado y Finalizado'), ('REPROBADO', 'Examen Reprobado (Requiere Reintento)')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajeinterno',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='archivo_word',
            field=models.FileField(upload_to='plantillas_docs/'),
        ),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='puntos_si',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.colaborador'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='sesion_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='intranet.colaborador'),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='intranet.colaborador'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
