# Generated by Django 6.0.6 on 2026-06-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_alter_asistencia_colaborador_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoReclutamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='DNI/CE')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('estado_candidato', models.CharField(max_length=50)),
                ('sede', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidato de Reclutamiento',
                'verbose_name_plural': 'Candidatos de Reclutamiento',
            },
        ),
    ]
