# Generated by Django 6.0.6 on 2026-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_candidatoreclutamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatoreclutamiento',
            name='canal',
            field=models.CharField(blank=True, default='Meta Ads', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidatoreclutamiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatoreclutamiento',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI/CE'),
        ),
        migrations.AlterField(
            model_name='candidatoreclutamiento',
            name='sede',
            field=models.CharField(default='No Asignado', max_length=50),
        ),
    ]
