# Generated by Django 6.0.6 on 2026-06-16 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_candidatoreclutamiento_canal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='intranet.candidatoreclutamiento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Llamada', 'Llamada'), ('WhatsApp', 'WhatsApp'), ('Correo', 'Correo')], max_length=20)),
                ('detalle', models.TextField(help_text='¿Qué se conversó con el candidato?')),
                ('fecha_contacto', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='intranet.candidatoreclutamiento')),
            ],
        ),
    ]
