# Generated by Django 6.0.6 on 2026-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_historialestado_registrocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatoreclutamiento',
            name='canal',
            field=models.CharField(blank=True, default='Por Definir', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatoreclutamiento',
            name='sede',
            field=models.CharField(blank=True, default='No Asignado', max_length=50, null=True),
        ),
    ]
