# Generated by Django 6.0.6 on 2026-06-18 13:41

import intranet.models.documentos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_alter_candidatoreclutamiento_canal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentogenerado',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=intranet.models.documentos.ruta_dinamica_pdf),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='archivo',
            field=models.FileField(upload_to=intranet.models.documentos.ruta_dinamica_personal),
        ),
    ]
