# Generated by Django 6.0.6 on 2026-06-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_alter_documentogenerado_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaevaluacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='preguntaevaluacion',
            name='configuracion_json',
        ),
        migrations.RemoveField(
            model_name='preguntaevaluacion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='preguntaevaluacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='respuestacolaborador',
            name='respuesta_json',
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='orden_aleatorio',
            field=models.BooleanField(default=True, help_text='Mezclar las preguntas y alternativas'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='preguntas_a_mostrar',
            field=models.PositiveIntegerField(default=10, help_text='Ej: Mostrar solo 10 al azar de un Excel de 100'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncurso',
            name='puntaje_aprobatorio',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='preguntaevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_balotario', to='intranet.evaluacioncurso'),
        ),
        migrations.AlterField(
            model_name='preguntaevaluacion',
            name='puntos',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='respuestacolaborador',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_examen', to='intranet.matriculacurso'),
        ),
        migrations.AlterField(
            model_name='respuestacolaborador',
            name='puntos_obtenidos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='intranet.preguntaevaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='respuestacolaborador',
            name='opciones_marcadas',
            field=models.ManyToManyField(blank=True, to='intranet.opcionrespuesta'),
        ),
    ]
