# Generated by Django 6.0.6 on 2026-06-19 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_alter_preguntaevaluacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Examen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Instrucciones')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('nota_aprobacion', models.DecimalField(decimal_places=2, default=14.0, max_digits=4, verbose_name='Nota de Aprobación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('score_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Nota Final')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado'), ('EXPIRADO', 'Expirado')], default='EN_PROGRESO', max_length=20)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_evaluacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Intentos de Exámenes',
            },
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='examenes/', verbose_name='Imagen Opcional')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='intranet.examen')),
            ],
            options={
                'verbose_name': 'Pregunta de Examen',
                'verbose_name_plural': 'Preguntas de Examen',
            },
        ),
        migrations.CreateModel(
            name='OpcionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto de la Opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='intranet.preguntaexamen')),
            ],
            options={
                'verbose_name': 'Opción de Examen',
                'verbose_name_plural': 'Opciones de Examen',
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='intranet.intento')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.opcionexamen')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.preguntaexamen')),
            ],
            options={
                'verbose_name': 'Respuesta de Usuario',
                'verbose_name_plural': 'Respuestas de Usuarios',
            },
        ),
    ]
