# Generated by Django 6.0.6 on 2026-06-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_examen_intento_preguntaexamen_opcionexamen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaexamen',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='intento',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='intento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='intento',
        ),
        migrations.RemoveField(
            model_name='opcionexamen',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='opcion_seleccionada',
        ),
        migrations.RemoveField(
            model_name='respuestausuario',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='activa',
            field=models.BooleanField(default=True, help_text='Permite ocultar el examen temporalmente'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo límite en minutos'),
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.DeleteModel(
            name='Intento',
        ),
        migrations.DeleteModel(
            name='OpcionExamen',
        ),
        migrations.DeleteModel(
            name='PreguntaExamen',
        ),
        migrations.DeleteModel(
            name='RespuestaUsuario',
        ),
    ]
