# Generated by Django 6.0.6 on 2026-06-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_remove_preguntaexamen_examen_remove_intento_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoinduccion',
            name='publico_general',
            field=models.BooleanField(default=True, help_text='Si está activo, TODOS los empleados lo verán.'),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='rol_permitido',
            field=models.CharField(blank=True, choices=[('ASESOR', 'Asesor'), ('BACKOFFICE', 'Backoffice'), ('CALIDAD', 'Calidad'), ('SUPERVISOR', 'Supervisor'), ('SISTEMAS', 'Sistemas'), ('ADMINISTRATIVO', 'Administrativo'), ('RRHH', 'Recursos Humanos'), ('GERENCIA', 'Gerencia')], help_text='Mostrar SOLO a este Rol (Déjalo en blanco para no filtrar por rol).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cursoinduccion',
            name='cartera_vinculada',
            field=models.ForeignKey(blank=True, help_text='Mostrar SOLO a esta Cartera/Campaña.', null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.negocio'),
        ),
    ]
