# Generated by Django 6.0.6 on 2026-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_cursoinduccion_publico_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncurso',
            name='puntos_premio',
            field=models.IntegerField(default=50, help_text='Puntos que gana el asesor al aprobar'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='tiempo_limite_minutos',
            field=models.IntegerField(default=0, help_text='0 significa sin límite de tiempo'),
        ),
    ]
