# Generated by Django 6.0.6 on 2026-06-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_evaluacioncurso_puntos_premio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacioncurso',
            name='duracion_minutos',
        ),
        migrations.CreateModel(
            name='LeccionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_video', models.URLField(blank=True, help_text='URL del video (Ej: YouTube embed)', null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='lms_materiales/')),
                ('orden', models.IntegerField(default=1, help_text='Orden en el que aparece la lección')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='intranet.cursoinduccion')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.colaborador')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.leccioncurso')),
            ],
        ),
    ]
