# Generated by Django 6.0.6 on 2026-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_remove_evaluacioncurso_duracion_minutos_leccioncurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoinduccion',
            name='subcartera_vinculada',
            field=models.CharField(blank=True, help_text="Ej: 'Mora Temprana' o 'Castigada'. Déjalo en blanco si es para toda la cartera.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leccioncurso',
            name='url_presentacion_canva',
            field=models.URLField(blank=True, help_text="Pega aquí el enlace de 'Ver públicamente' o 'Insertar' de Canva, Genially o Google Slides.", null=True),
        ),
        migrations.AlterField(
            model_name='cursoinduccion',
            name='rol_permitido',
            field=models.CharField(blank=True, choices=[('ASESOR', 'Asesor'), ('BACKOFFICE', 'Backoffice'), ('CALIDAD', 'Calidad'), ('SUPERVISOR', 'Supervisor'), ('SISTEMAS', 'Sistemas'), ('ADMINISTRATIVO', 'Administrativo'), ('RRHH', 'Recursos Humanos'), ('GERENCIA', 'Gerencia')], help_text='Mostrar SOLO a este Rol (Ej: Solo Supervisores).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cursoinduccion',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'Cultura General RJ (Para todos)'), ('CARTERA', 'Específico por Cartera / Negocio'), ('HABILIDADES', 'Desarrollo de Habilidades (Opcional/Secundario)'), ('INDUCCION', 'Módulo de Onboarding / Inducción')], default='GENERAL', max_length=20),
        ),
    ]
