# Generated by Django 6.0.6 on 2026-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0014_cursoinduccion_subcartera_vinculada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoinduccion',
            name='subcartera_vinculada',
            field=models.CharField(blank=True, help_text='Para Academia: aquí se guarda la categoría del curso. Para Inducción: aquí se guarda la subcartera.', max_length=100, null=True),
        ),
    ]
