# Generated by Django 6.0.6 on 2026-06-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_alter_cursoinduccion_subcartera_vinculada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='subcartera',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='intranet.area'),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='area_permitida',
            field=models.ForeignKey(blank=True, help_text='Mostrar SOLO a esta área.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_permitidos', to='intranet.area'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='intranet.area')),
            ],
            options={
                'unique_together': {('area', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='intranet.cargo'),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='cargo_permitido',
            field=models.ForeignKey(blank=True, help_text='Mostrar SOLO a este cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_permitidos', to='intranet.cargo'),
        ),
    ]
