# Generated by Django 6.0.6 on 2026-06-26 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0016_area_colaborador_subcartera_colaborador_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='area_permitida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_permitidas', to='intranet.area'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='cargo_permitido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_permitidas', to='intranet.cargo'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='cartera_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_permitidas', to='intranet.negocio'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='publico_general',
            field=models.BooleanField(default=True, help_text='Si está activo, todos podrán verla.'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='rol_permitido',
            field=models.CharField(blank=True, choices=[('ASESOR', 'Asesor'), ('BACKOFFICE', 'Backoffice'), ('CALIDAD', 'Calidad'), ('SUPERVISOR', 'Supervisor'), ('SISTEMAS', 'Sistemas'), ('ADMINISTRATIVO', 'Administrativo'), ('RRHH', 'Recursos Humanos'), ('GERENCIA', 'Gerencia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='subcartera_vinculada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
