# Generated by Django 6.0.6 on 2026-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_encuesta_area_permitida_encuesta_cargo_permitido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='descripcion_perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/fotos/'),
        ),
    ]
