# Generated by Django 6.0.6 on 2026-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0018_colaborador_descripcion_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
