# Generated by Django 6.0.6 on 2026-06-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_alter_colaborador_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSAJE', 'Mensaje'), ('TICKET', 'Ticket'), ('VACACIONES', 'Vacaciones'), ('ALERTA', 'Alerta')], db_index=True, default='ALERTA', max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('detalle', models.CharField(blank=True, default='', max_length=300)),
                ('url_destino', models.CharField(blank=True, default='', max_length=300)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
