# Generated by Django 6.0.6 on 2026-06-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModuloLMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=220)),
                ('icono', models.CharField(blank=True, default='bi-grid-1x2-fill', max_length=40)),
                ('color', models.CharField(blank=True, default='#183D74', max_length=7)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='certificado_habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='duracion_estimada_horas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='nivel',
            field=models.CharField(choices=[('BASICO', 'Basico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='BASICO', max_length=20),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='obligatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='orden_sugerido',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='intentos_maximos',
            field=models.PositiveIntegerField(default=1, help_text='0 permite intentos ilimitados'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='mostrar_resultado_inmediato',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='permitir_revision_respuestas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='retroalimentacion_final',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='intentos_realizados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='categoria_lms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='intranet.categoriamodulolms'),
        ),
    ]
