# Generated by Django 6.0.6 on 2026-06-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0021_categoriamodulolms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='descripcion_ayuda',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='obligatoria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='valor_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='valor_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('ABIERTA', 'Pregunta Abierta (Texto Libre)'), ('CERRADA', 'Pregunta Cerrada (Opciones Sí / No)'), ('OPCION_UNICA', 'Opción Única (Lista de Alternativas)'), ('ESCALA_1_5', 'Escala 1 a 5'), ('FECHA', 'Fecha')], default='ABIERTA', max_length=20),
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=180)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='intranet.pregunta')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='valor_opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='intranet.opcionpregunta'),
        ),
    ]
