# Generated by Django 6.0.6 on 2026-06-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0022_alter_pregunta_options_pregunta_descripcion_ayuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoinduccion',
            name='curso_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones', to='intranet.cursoinduccion'),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='estado_publicacion',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], db_index=True, default='PUBLICADO', max_length=20),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='modulo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_hijos', to='intranet.cursoinduccion'),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='prerequisito_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_dependientes', to='intranet.cursoinduccion'),
        ),
        migrations.AddField(
            model_name='cursoinduccion',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leccioncurso',
            name='paquete_scorm_url',
            field=models.URLField(blank=True, help_text='URL del paquete SCORM u objeto interactivo', null=True),
        ),
        migrations.AddField(
            model_name='leccioncurso',
            name='url_simulador',
            field=models.URLField(blank=True, help_text='URL de simulador o laboratorio práctico', null=True),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='certificado_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='certificado_emitido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='certificado_vigente_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='depende_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_condicionales', to='intranet.pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='valor_disparador',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='dificultad',
            field=models.CharField(choices=[('BASICO', 'Basico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], db_index=True, default='BASICO', max_length=20),
        ),
        migrations.AddField(
            model_name='preguntaevaluacion',
            name='tema',
            field=models.CharField(blank=True, default='General', max_length=120),
        ),
        migrations.CreateModel(
            name='RutaInduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('rol_objetivo', models.CharField(blank=True, choices=[('ASESOR', 'Asesor'), ('BACKOFFICE', 'Backoffice'), ('CALIDAD', 'Calidad'), ('SUPERVISOR', 'Supervisor'), ('SISTEMAS', 'Sistemas'), ('ADMINISTRATIVO', 'Administrativo'), ('RRHH', 'Recursos Humanos'), ('GERENCIA', 'Gerencia')], max_length=50, null=True)),
                ('subcartera_objetivo', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('area_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_induccion', to='intranet.area')),
                ('cartera_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_induccion', to='intranet.negocio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutaInduccionModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_induccion', to='intranet.cursoinduccion')),
                ('prerequisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desbloquea', to='intranet.rutainduccionmodulo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intranet.rutainduccion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'modulo')},
            },
        ),
    ]
