# Generated by Django 6.0.6 on 2026-06-30 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0023_cursoinduccion_curso_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtajoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('icono', models.CharField(default='bi-star-fill', max_length=50)),
                ('color', models.CharField(default='primary', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atajos_configurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
