# Generated by Django 6.0.6 on 2026-06-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0024_atajousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FelicitacionCumpleaños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('privado', models.BooleanField(default=False, help_text='Si es true, solo el destinatario lo ve. Si es false, aparece en el muro.')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felicitaciones_recibidas', to='intranet.colaborador')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felicitaciones_enviadas', to='intranet.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTRELLA', 'Estrella de Desempeño 🌟'), ('COMPAÑERO', 'Gran Compañero 🤝'), ('INNOVADOR', 'Idea Innovadora 💡'), ('LIDERAZGO', 'Liderazgo Inspirador 👑'), ('SOLUCIONADOR', 'Solucionador de Problemas 🛠️')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos_dados', to='intranet.colaborador')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos_recibidos', to='intranet.colaborador')),
            ],
        ),
    ]
