# Generated by Django 6.0.6 on 2026-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0025_colaborador_fecha_nacimiento_felicitacioncumpleaños_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconocimiento',
            name='tipo',
            field=models.CharField(choices=[('ESTRELLA', 'Estrella de Desempeño 🌟'), ('COMPAÑERO', 'Gran Compañero 🤝'), ('INNOVADOR', 'Idea Innovadora 💡'), ('LIDERAZGO', 'Liderazgo Inspirador 👑'), ('SOLUCIONADOR', 'Solucionador de Problemas 🛠️'), ('MIGAJERO', 'El Más Migajero (De a poquitos se llena el tarrito) 🪙')], max_length=50),
        ),
    ]
