# Generated by Django 6.0.6 on 2026-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0026_alter_reconocimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='sede',
            field=models.CharField(choices=[('LIMA1', 'Lima 1 (Lince)'), ('LIMA2', 'Lima 2 (San Isidro, Lima)'), ('TRUJILLO1', 'Trujillo 1 (San Isidro, Trujillo)'), ('TRUJILLO2', 'Trujillo 2 (Ayacucho)')], db_index=True, default='LIMA1', max_length=20),
        ),
    ]
