# Generated by Django 6.0.6 on 2026-06-30 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0027_colaborador_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudvacaciones',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='revisado_por',
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='aprobado_por_n1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_n1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='aprobado_por_n2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_n2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='aprobado_por_n3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_n3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='fecha_n1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='fecha_n2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='fecha_n3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='aprobado_por_n1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_n1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='aprobado_por_n2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_n2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='aprobado_por_n3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_n3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comentarios_resolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_n1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_n2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_n3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_N1', 'Pendiente (Supervisor)'), ('PENDIENTE_N2', 'Pendiente (Sede)'), ('PENDIENTE_N3', 'Pendiente (RRHH)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE_N1', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_N1', 'Pendiente (Supervisor)'), ('PENDIENTE_N2', 'Pendiente (Sede)'), ('PENDIENTE_N3', 'Pendiente (RRHH)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE_N1', max_length=20),
        ),
    ]
