# Generated by Django 6.0.6 on 2026-06-30 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0028_remove_solicitudvacaciones_revisado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='aprobado_por_n1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_n1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='aprobado_por_n2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_n2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='aprobado_por_n3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_n3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_N1', 'Pendiente (Supervisor)'), ('PENDIENTE_N2', 'Pendiente (Sede)'), ('PENDIENTE_N3', 'Pendiente (RRHH)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE_N1', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='aprobado_por_n1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_n1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='aprobado_por_n2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_n2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='aprobado_por_n3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_n3', to=settings.AUTH_USER_MODEL),
        ),
    ]
