# Generated by Django 6.0.6 on 2026-07-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0029_alter_solicitudvacaciones_aprobado_por_n1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('meta_default', models.DecimalField(decimal_places=2, default=100.0, help_text='Meta esperada por defecto (ej. 100%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Evaluación Anual 2026, Q3 2026', max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Evaluación'), ('AUTOEVALUADO', 'Autoevaluado por el Colaborador'), ('EVALUADO', 'Evaluado por el Supervisor'), ('CERRADO', 'Evaluación Cerrada')], default='PENDIENTE', max_length=20)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio ponderado de 0 a 100', max_digits=5, null=True)),
                ('potencial', models.CharField(blank=True, choices=[('BAJO', 'Bajo Potencial'), ('MEDIO', 'Medio Potencial'), ('ALTO', 'Alto Potencial')], help_text='Potencial para la Matriz 9-Box', max_length=10, null=True)),
                ('feedback_supervisor', models.TextField(blank=True, help_text='Comentarios generales del supervisor', null=True)),
                ('autoevaluacion_comentario', models.TextField(blank=True, help_text='Comentarios del colaborador', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to='intranet.colaborador')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='intranet.colaborador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='intranet.periodoevaluacion')),
            ],
            options={
                'unique_together': {('periodo', 'colaborador')},
            },
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('resultado_real', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de cumplimiento de la meta (0-100+)', max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='intranet.evaluaciondesempeno')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.kpi')),
            ],
            options={
                'unique_together': {('evaluacion', 'kpi')},
            },
        ),
    ]
