# Generated by Django 6.0.6 on 2026-07-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0030_kpi_periodoevaluacion_evaluaciondesempeno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_asignados', models.DecimalField(decimal_places=2, default=15.0, help_text='Base de días anuales (ej. 15 o 30)', max_digits=5)),
                ('dias_extra', models.DecimalField(decimal_places=2, default=0.0, help_text='Días adicionales por compensación u otros', max_digits=5)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_vacaciones', to='intranet.colaborador')),
            ],
        ),
    ]
