# Generated by Django 6.0.6 on 2026-07-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0031_saldovacaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_puntos', models.PositiveIntegerField(help_text='Costo en puntos para canjear')),
                ('stock', models.PositiveIntegerField(default=10, help_text='Cantidad disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='gamificacion/premios/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='puntos_acumulados',
            field=models.PositiveIntegerField(default=0, help_text='Total histórico para ranking'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='puntos_disponibles',
            field=models.PositiveIntegerField(default=0, help_text='Saldo actual para canjear premios'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='puntos_otorgados',
            field=models.PositiveIntegerField(default=10, help_text='Puntos sumados al receptor por este Kudo'),
        ),
        migrations.CreateModel(
            name='CanjePremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Entrega'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes_solicitados', to='intranet.colaborador')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='intranet.catalogopremio')),
            ],
        ),
    ]
