# Generated by Django 6.0.6 on 2026-07-01 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0032_catalogopremio_colaborador_puntos_acumulados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilladocumento',
            name='archivo_word',
        ),
        migrations.AddField(
            model_name='documentogenerado',
            name='contenido_generado',
            field=models.TextField(blank=True, help_text='Contenido estático final firmado', null=True),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='contenido_html',
            field=models.TextField(blank=True, help_text='Contenido HTML de la plantilla con variables', null=True),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
