# Generated by Django 6.0.6 on 2026-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0033_remove_plantilladocumento_archivo_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_N1', 'Pendiente (Supervisor)'), ('PENDIENTE_N2', 'Pendiente (Sede)'), ('PENDIENTE_N3', 'Pendiente (RRHH)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ELIMINADO_POR_USUARIO', 'Eliminado por Autor')], db_index=True, default='PENDIENTE_N1', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_N1', 'Pendiente (Supervisor)'), ('PENDIENTE_N2', 'Pendiente (Sede)'), ('PENDIENTE_N3', 'Pendiente (RRHH)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ELIMINADO_POR_USUARIO', 'Eliminado por Autor')], db_index=True, default='PENDIENTE_N1', max_length=30),
        ),
    ]
