# Generated by Django 6.0.6 on 2026-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0035_colaborador_permitir_mensajes_cumpleanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='carteras_secundarias',
            field=models.ManyToManyField(blank=True, related_name='colaboradores_secundarios', to='intranet.negocio'),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_N1', 'Pendiente (Supervisor)'), ('PENDIENTE_N2', 'Pendiente (Administrador)'), ('PENDIENTE_N3', 'Pendiente (RRHH)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ELIMINADO_POR_USUARIO', 'Eliminado por Autor')], db_index=True, default='PENDIENTE_N1', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_N1', 'Pendiente (Supervisor)'), ('PENDIENTE_N2', 'Pendiente (Administrador)'), ('PENDIENTE_N3', 'Pendiente (RRHH)'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ELIMINADO_POR_USUARIO', 'Eliminado por Autor')], db_index=True, default='PENDIENTE_N1', max_length=30),
        ),
    ]
