# Generated by Django 6.0.6 on 2026-07-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0036_colaborador_carteras_secundarias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoOrganigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('DIVISION', 'División'), ('AREA', 'Área'), ('CARGO', 'Cargo'), ('PERSONA', 'Colaborador')], default='AREA', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('color', models.CharField(default='#16213e', max_length=20)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intranet.colaborador')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='intranet.nodoorganigrama')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
