# Generated by Django 6.0.6 on 2026-07-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0037_nodoorganigrama'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(default='🏆', help_text='Emoji representativo', max_length=10)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='tipo',
            field=models.CharField(choices=[('ESTRELLA', 'Estrella de Desempeño 🌟'), ('COMPAÑERO', 'Gran Compañero 🤝'), ('INNOVADOR', 'Idea Innovadora 💡'), ('LIDERAZGO', 'Liderazgo Inspirador 👑'), ('SOLUCIONADOR', 'Solucionador de Problemas 🛠️')], max_length=50),
        ),
        migrations.CreateModel(
            name='VotoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='intranet.colaborador')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='intranet.categoriavotacion')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to='intranet.colaborador')),
            ],
            options={
                'unique_together': {('votante', 'categoria', 'mes', 'anio')},
            },
        ),
    ]
